version: "3"
services:
  TEMPLATE:
    build:
      context: .
    container_name: TEMPLATE
    restart: unless-stopped
    volumes:
      - ./server:/server
      - /etc/localtime:/etc/localtime:ro
    network_mode: bridge
    ports:
      - target: 25565
        published: 25565
        protocol: tcp
        mode: host
